node_id: 1
base_id: 1
serial_port: "/dev/ttyS0"
baud_rate: 115200
tx_interval: 1
role: "scout"
waypoints:
  - [33.686377, -117.789653]
  - [33.685965, -117.790052]
  - [33.685647, -117.789599]
  - [33.686268, -117.788997]
  - [33.686559, -117.789462]
  - [33.686377, -117.789653]
# BotCar Configuration File
# Ensure the Log_Directory exists before running the BotCarNode.
# Example: mkdir -p ./logs

Node_ID: "AMU_01"       # Unique identifier for this botCar
Mission_Logging: Y      # Enable or disable mission logging
Log_Directory: "./logs" # Directory where mission logs will be stored

 
